// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvfilfZ5lYyQPuKHFWdpfVFY1MYMDOSsM',
    appId: '1:353573133208:android:efcce65b200d62e53da9ed',
    messagingSenderId: '353573133208',
    projectId: 'vibetalk-7672c',
    storageBucket: 'vibetalk-7672c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASWKyfZILdpGQZLylv8xUVyR-qrH_xVLI',
    appId: '1:353573133208:ios:b9b851c71f66d85f3da9ed',
    messagingSenderId: '353573133208',
    projectId: 'vibetalk-7672c',
    storageBucket: 'vibetalk-7672c.firebasestorage.app',
    iosBundleId: 'com.vibetalk.vibetalk',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAIYRw9kS2ZzNZFL0AchyYJMjEN6s31nA',
    appId: '1:353573133208:web:8f532139a5619ba73da9ed',
    messagingSenderId: '353573133208',
    projectId: 'vibetalk-7672c',
    authDomain: 'vibetalk-7672c.firebaseapp.com',
    storageBucket: 'vibetalk-7672c.firebasestorage.app',
    measurementId: 'G-4738CMB4WK',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAIYRw9kS2ZzNZFL0AchyYJMjEN6s31nA',
    appId: '1:353573133208:web:85828200c3df0b443da9ed',
    messagingSenderId: '353573133208',
    projectId: 'vibetalk-7672c',
    authDomain: 'vibetalk-7672c.firebaseapp.com',
    storageBucket: 'vibetalk-7672c.firebasestorage.app',
    measurementId: 'G-W774G14HJH',
  );

}